2019-01-20 10:49:56,375 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
    for x, y in mood, dateTime_formatted:
ValueError: too many values to unpack (expected 2)
2019-01-20 10:50:39,724 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
    for x, y in mood, dateTime_formatted:
ValueError: too many values to unpack (expected 2)
2019-01-20 10:57:34,058 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
ValueError: too many values to unpack (expected 2)
2019-01-20 10:58:20,210 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
ValueError: too many values to unpack (expected 2)
2019-01-20 10:58:24,829 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
ValueError: too many values to unpack (expected 2)
2019-01-20 10:58:40,936 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
ValueError: too many values to unpack (expected 2)
