2019-01-20 10:59:32,545 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
ValueError: too many values to unpack (expected 2)
2019-01-20 10:59:37,317 ERROR: Exception on /subject/1 [GET] [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/routes.py", line 382, in subject
ValueError: too many values to unpack (expected 2)
2019-01-20 11:00:07,816 INFO: Microblog startup [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/__init__.py:49]
2019-01-21 19:25:14,773 INFO: Microblog startup [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/__init__.py:49]
2019-01-22 19:39:28,150 INFO: Microblog startup [in /mnt/c/Users/Kwaz9/Desktop/Byte/frg/app/__init__.py:49]
